apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notificationapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificationapi
  template:
    spec:
      containers:
        - name: notificationapi
          imagePullPolicy: Always
          image: notificationapi
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: notificationapi-service
spec:
  selector:
    app: project2
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80