apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi
spec:
  selector:
    matchLabels:
      app: notificationapi
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: notificationapi
    spec:
      containers:
      - name: notificationapi
        image: northamerica-northeast2-docker.pkg.dev/revature-346918/gcp-docker/notificationapi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notificationapi-service
spec:
  selector:
    app: project2
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080