apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  EMAIL_PASS: cGFzc3dvcmQ=
  TWILIO_ACCOUNT_TOKEN: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MAPS_API_KEY: cGFzc3dvcmQ=
  STRIPE_KEY: cGFzc3dvcmQ=