apiVersion: apps/v1
kind: Deployment
metadata:
  name: directionsapi
spec:
  selector:
    matchLabels:
      app: directionsapi
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: directionsapi
    spec:
      containers:
      - name: directionsapi
        image: directionsapi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: directionsapi-service
spec:
  selector:
    app: directionsapi
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8081