apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
      tier: database
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
        tier: database
    spec:
      containers:
      - name: mysqldb
        image: mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    tier: database
spec:
  selector:
    app: mysqldb
    tier: database
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP