apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi
spec:
  selector:
    matchLabels:
      app: notificationapi
  replicas: 1
  template:
    metadata:
      labels:
        app: notificationapi
    spec:
      containers:
      - name: notificationapi
        image: notificationapi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notificationapi-service
spec:
  selector:
    app: notificationapi
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080