apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: p2
  name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: p2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Programs\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: p2
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_PASSWORD
                  optional: false
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_URL
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_USERNAME
                  optional: false
            - name: MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: MAPS_API_KEY
                  optional: false
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: STRIPE_KEY
                  optional: false
          image: northamerica-northeast2-docker.pkg.dev/devops-javasre/test-p2/api2:latest
          imagePullPolicy: Always
          name: api2
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api2
  name: api2
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8081
  selector:
    io.kompose.service: p2
status:
  loadBalancer: {}
