apiVersion: v1
kind: Service
metadata:
  name: api2
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8081
  selector:
    app: api2
status:
  loadBalancer: {}
