---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api2-deployment"
  namespace: "default"
  labels:
    app: "api2-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "api2-deployment"
  template:
    metadata:
      labels:
        app: "api2-deployment"
    spec:
      containers:
      - name: "api2-1"
        image: "northamerica-northeast2-docker.pkg.dev/devops-javasre/test-p2/api2:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api2-deployment-hpa-iqdq"
  namespace: "default"
  labels:
    app: "api2-deployment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api2-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
