apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api2
  name: api2
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8081
  selector:
    io.kompose.service: api2
status:
  loadBalancer: {}
