apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api2
  name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  strategy: {}
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_PASSWORD
                  optional: false
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_URL
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_USERNAME
                  optional: false
            - name: MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: MAPS_API_KEY
                  optional: false
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: STRIPE_KEY
                  optional: false
          image: northamerica-northeast2-docker.pkg.dev/devops-javasre/test-p2/api2:latest
          imagePullPolicy: Always
          name: api2
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
