apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api2
  name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Programs\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: api2
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_PASSWORD
                  optional: false
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_URL
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_USERNAME
                  optional: false
            - name: MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: MAPS_API_KEY
                  optional: false
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: STRIPE_KEY
                  optional: false
          image: api2:latest
          imagePullPolicy: Never
          name: api2
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
