apiVersion: v1
kind: Service
metadata:
  name: deliveryapi
spec:
  type: LoadBalancer
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8080
  selector:
    app: deliveryapi
status:
  loadBalancer: {}