apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: graf
  name: graf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graf
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Programs\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: graf
    spec:
      containers:
        - image: grafana/grafana
          imagePullPolicy: Never
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
