apiVersion: v1
kind: Service
metadata:
  name: notificationapi
spec:
  type: LoadBalancer
  ports:
    - name: "7000"
      port: 7000
      targetPort: 8080
  selector:
    app: notificationapi
status:
  loadBalancer: {}
