apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: notificationapi
  name: notificationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notificationapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Programs\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: notificationapi
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_PASSWORD
                  optional: false
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_URL
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_USERNAME
                  optional: false
          image: notificationapi:latest
          imagePullPolicy: Never
          name: notificationapi
          resources: {}
      restartPolicy: Always
status: {}
