apiVersion: v1
kind: Service
metadata:
  name: notificationapi
spec:
  type: LoadBalancer
  ports:
    - name: "10553"
      port: 10553
      targetPort: 8080
  selector:
    app: notificationapi
status:
  loadBalancer: {}
