apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notificationapi
  name: notificationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationapi
  strategy: {}
  template:
    metadata:
      labels:
        app: notificationapi
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_PASSWORD
                  optional: false
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_URL
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apikeys
                  key: DB_USERNAME
                  optional: false
          image: northamerica-northeast2-docker.pkg.dev/devops-javasre/test-p2/notificationapi:latest
          imagePullPolicy: Never
          name: notificationapi
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
